(SELECT distinct(PNO)
From EMPLOYEE, WORKS_ON
WHERE LNAME = "Wong" AND SSN = ESSN)

UNION

(SELECT distinct(pnumber)
FROM PROJECT, DEPARTMENT, EMPLOYEE
WHERE DNUM = DNUMBER AND MGRSSN = SSN AND LNAME = "Wong");