WITH JF_TITLE AS(
	SELECT TITLE_ID
	FROM (SELECT PERSON_ID FROM PEOPLE WHERE NAME='Jennifer Lawrence') AS JF
	JOIN CREW C ON JF.PERSON_ID = C.PERSON_ID
),

JF_TITLE_COUNT AS(
	SELECT COUNT(TITLE_ID) AS TITLE_COUNT
	FROM JF_TITLE
),

PEOPLE_JF AS(
	SELECT P.NAME AS NAME, COUNT(TITLE_ID) AS SHARED_TITLE
    FROM PEOPLE P JOIN CREW C ON P.PERSON_ID=C.PERSON_ID
    WHERE TITLE_ID IN (SELECT TITLE_ID FROM JF_TITLE)
    GROUP BY P.NAME
)

SELECT NAME
FROM PEOPLE_JF
WHERE SHARED_TITLE = (SELECT TITLE_COUNT FROM JF_TITLE_COUNT)
ORDER BY NAME;


