SELECT distinct P.NAME, P.BORN
FROM CREW AS C 
JOIN PEOPLE AS P ON C.PERSON_ID=P.PERSON_ID
JOIN TITLES AS T ON C.TITLE_ID=T.TITLE_ID 
WHERE (C.CATEGORY='actor') AND (P.BORN IS NOT NULL) AND (T.PREMIERED - P.BORN) <= 20 AND (T.PREMIERED - P.BORN) >= 0
ORDER BY P.NAME;