SELECT P1.BORN, P1.NAME, P2.NAME
FROM PEOPLE P1 JOIN CREW C1 ON P1.PERSON_ID=C1.PERSON_ID AND CATEGORY='actress'
JOIN PEOPLE P2 ON P1.BORN=P2.BORN AND P1.BORN IS NOT NULL 
JOIN CREW C2 ON P2.PERSON_ID=C2.PERSON_ID AND C2.CATEGORY='actor'
WHERE C1.title_id=C2.title_id
GROUP BY 1,2,3
ORDER BY 1,2,3;
