SELECT premiered AS YEAR, COUNT(TITLE_ID) AS MOVIE_COUNT
FROM TITLES
WHERE GENRES LIKE '%Comedy%' AND PREMIERED IS NOT NULL AND TITLE_TYPE='movie'
GROUP BY 1
HAVING COUNT(TITLE_ID) > 0
ORDER BY premiered;