SELECT DISTINCT NAME
FROM CREW JOIN PEOPLE ON CREW.PERSON_ID=PEOPLE.PERSON_ID
WHERE CATEGORY='ACTRESS' AND TITLE_ID IN 
										(SELECT DISTINCT T.TITLE_ID
										FROM AKAS AS A JOIN TITLES AS T ON A.TITLE_ID=T.TITLE_ID
										WHERE REGION='JP' AND PREMIERED BETWEEN 1991 AND 2000 AND GENRES LIKE '%ACTION%' AND TITLE_TYPE='movie')
ORDER BY NAME;