CREATE VIEW CREW_PEOPLE AS (
	SELECT TITLE_ID, CATEGORY, JOB, C.PERSON_ID, NAME, BORN, DIED
    FROM PEOPLE P JOIN CREW C ON P.PERSON_ID=C.PERSON_ID
);

SELECT DISTINCT NAME 
FROM CREW_PEOPLE
WHERE TITLE_ID IN 
(select TITLE_ID
FROM CREW_PEOPLE
WHERE NAME='Jennifer Lawrence');